spring.application.name=FoodDeliveryApp

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://db.suslvvrioxkdeubbrtrf.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

paypal.client-id=${PAYPAL_CLIENT_ID}
paypal.client-secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.cache.type=simple

# Logging configuration
logging.level.org.hibernate.SQL=DEBUG
